# Tuple/List Bug 
input_video: '/mnt/49418012-cfa6-4af1-86d8-c0fb55ae6501/Gaze_Estimation/Datasets/AWL_20052020/case24/04_area1_signage1_2020_05_15_10_40_29.mp4'
output_folder: './'

camera: 
  is_export: False
  height: None
  camera_name: 'camera'
  keep_original_size: False
  fps: 25

face:
  weight: '/mnt/49418012-cfa6-4af1-86d8-c0fb55ae6501/Gaze_Estimation/Gitlab_Code/src/graphs/face_mask_detection.params'
  det_threshold: 0.5
  area_threshold: 0
  target_size: [260,260]
  reverse_order: False
  color: [0,255,0]
